-- Die Aufteilung fällt weg, und mit ihr ihre Tabelle.
--
-- `001_init.sql` hielt je Aufnahme fest, ob sie lernt, steuert oder prüft.
-- Einmal vergeben, nie wieder geändert - denn eine Aufnahme, die einmal
-- geprüft hatte, durfte nie trainieren, sonst maß der Test das
-- Auswendiggelernte. Die Tabelle war der einzige Weg, diese Zusage über eine
-- gelöschte Aufnahme hinweg zu halten.
--
-- Seit September 2026 gibt es kein Testdrittel mehr. Gemessen wird mit
-- sechsfacher Kreuzvalidierung über den ganzen Korpus: Jede Aufnahme trägt der
-- Reihe nach eine Faltung, je Faltung läuft ein Training, und am Ende ist jede
-- Aufnahme genau einmal von einem Modell gehört worden, das sie nicht kannte.
-- In fünf von sechs Faltungen trainiert jede Aufnahme ohnehin; die Zusage, die
-- diese Tabelle schützte, gibt es also nicht mehr zu schützen.
--
-- Damit ist die Faltung nichts, was gespeichert werden müsste: Sie folgt der
-- Reihenfolge des Korpus und steht im Schnappschuss jedes Laufs. Eine Tabelle
-- daneben wäre eine zweite Wahrheit über dieselbe Sache - und die erste, die
-- nicht mehr stimmt, sobald jemand eine Aufnahme löscht.
--
-- **Was dabei verloren geht.** Die Zuteilungen der Läufe von vorher. Sie sind
-- nicht wiederherstellbar, und sie werden nicht gebraucht: Jeder alte Lauf
-- trägt seine Aufteilung in seinem eigenen Manifest, und das bleibt liegen.
DROP TABLE IF EXISTS aufteilung;
